services:
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password="${MYSQL_PASSWORD}" -s -e "SELECT 1;"
      interval: 3s
      retries: 10
      timeout: 3s
    volumes:
      - db_store:/var/lib/mysql
  php-apache:
    build: ./docker/php-apache
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
      - ./.env.local
    environment:
      DB_HOST: mysql:3306
    ports:
      - ${PHP_APACHE_PORT}:80
    volumes:
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./web:/var/www/html/web
      - ./.env:/var/www/html/.env
      - ./.env.local:/var/www/html/.env.local
      - ./wp-cli.yml:/var/www/html/wp-cli.yml
      - ./wp-install.sh:/tmp/wp-install.sh
volumes:
  db_store: {}
