services:
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 15
      timeout: 60s
    volumes:
      - db_store:/var/lib/mysql
  php-apache:
    build: ./docker/php-apache
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
      - ./.env.local
    environment:
      DB_HOST: mysql:3306
    ports:
      - ${PHP_APACHE_PORT}:80
    volumes:
      - .:/var/www/html
volumes:
  db_store: {}
